version: "3.4"
services:
  web:
    build: 
      context: "."
      dockerfile: "./docker/dev.Dockerfile"
    environment: 
      instance: "PPRD"
      service: "PPRD.ORARAC1"
      full_login: "{database_user}@pprd"
    volumes:
      - ./app/:/app